# EC2 provisioning variables

# If yes, always provision new instance
# If no, ansible use local tfstate file which in roles/ec2-provisioning/files directory.
ignore_tfstate: no

instance_name: klaytn-node
instance_type: t2.medium
# If not set, uses latest ami
instance_ami:
instance_key_pair: my-key
instance_subnet_id: subnet-1234567890
vpc_security_group_ids:
- sg-1234
- sg-5678

# Install klay and run variables
ansible_user: ec2-user
ansible_ssh_private_key_file: ~/.ssh/my-key.pem
