# EC2 provisioning variables
ignore_tfstate: true
instance_name: klaytn-baobab
instance_type: t2.medium
instance_ami: ami-0157b322879b1763a  # base-ami-220110
instance_key_pair: univ-common
instance_subnet_id: subnet-00e6cf140a602cdb2  # ap-northeast-2a
vpc_security_group_ids:
- sg-0216da6b546a73691  # POLICY-OPS
- sg-0d8a0fc42c3072fee  # POLICY-INTERNAL-ALL-ALLOW

# Install klay and run variables
ansible_user: ec2-user
ansible_ssh_private_key_file: ~/.ssh/univ-common.pem
